apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: airflow
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: airflow-dev
  chart:
    repository: https://marclamberti.github.io/airflow-eks-helm-chart
    name: airflow
    version: 1.0.0
  values:
    images.airflow.repository: "asia.gcr.io/warung-support/data_dockerlab"
    images.airflow.tag: "latest"
    fernetKey: "zTxhk7FuGqQVPZVoukLn5bGWOrgHzhQnBnaqAItcZGI="
    env:
      - name: "AIRFLOW__KUBERNETES__DAGS_IN_IMAGE"
        value: "True"
      - name: "AIRFLOW__KUBERNETES__NAMESPACE"
        value: "dev"
      - name: "AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY"
        value: "asia.gcr.io/warung-support/data_dockerlab"
      - name: "AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG"
        value: "latest"
      - name: "AIRFLOW__KUBERNETES__RUN_AS_USER"
        value: "50000"
      - name: "AIRFLOW__CORE__LOAD_EXAMPLES"
        value: "False"
    executor: "KubernetesExecutor"
    # dags:
    #   persistence:
    #     enabled: false
    #   gitSync:
    #     enabled: true
    #     repo: git@github.com:Yuriowindiatmoko2401/airflow-dags.git
    #     branch: master
    #     maxFailures: 0
    #     subPath: ""
    #     sshKeySecret: airflow-ssh-secret
    #     wait: 60

    