apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: airflow
  namespace: dev
spec:
  releaseName: airflow-dev
  chart:
    repository: https://marclamberti.github.io/airflow-eks-helm-chart
    name: airflow
    version: 1.0.0
  values:
    images:
      airflow:
        repository: "apache/airflow"
        tag: "2.0.0"
    fernetKey: "zTxhk7FuGqQVPZVoukLn5bGWOrgHzhQnBnaqAItcZGI="
    env:
      - name: "AIRFLOW__KUBERNETES__DAGS_IN_IMAGE"
        value: "False"
      - name: "AIRFLOW__KUBERNETES__NAMESPACE"
        value: "dev"
      - name: "AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY"
        value: "apache/airflow"
      - name: "AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG"
        value: "2.0.0"
      - name: "AIRFLOW__KUBERNETES__RUN_AS_USER"
        value: "50000"
      - name: "AIRFLOW__CORE__LOAD_EXAMPLES"
        value: "False"
      # - name: "AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH"
      #   value: "repo/"
      # - name: "AIRFLOW__KUBERNETES__GIT_SYNC_RUN_AS_USER"
      #   value: "50000"
      # - name: "AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT"
      #   value: "/opt/airflow/dags/repo/"
      # - name: "AIRFLOW__KUBERNETES__DAGS_VOLUME_MOUNT_POINT"
      #   value: "/opt/airflow/dags/repo/"
    executor: "KubernetesExecutor"
    dags:
      persistence:
        enabled: false
      gitSync:
        enabled: true
        repo: git@github.com:Yuriowindiatmoko2401/airflow-dags.git
        branch: master
        dest: "repo"
        maxFailures: 0
        subPath: ""
        sshKeySecret: airflow-ssh-secret
        wait: 60

    